# Site settings
title: Tasso Evangelista
email: tasso@tassoevan.me
gravatar: 46f8da200f3fa1c9e05dae5d9e28521e
description: "Desenvolvedor&nbsp;Web e estudante de Engenharia&nbsp;Química."
theme_color: '#8851CC'
baseurl: ""
url: "http://tassoevan.github.io"
twitter_username: tassoevan
github_username:  tassoevan
bitbucket_username:  tassoevan
linkedin_username:  tassoevan
google_analytics_tracking_id: UA-31191590-3

# Build settings
gems:
    - jekyll-paginate
    - jekyll-sitemap
markdown: kramdown
permalink: pretty
sass:
    style: compressed
paginate: 10
paginate_path: "/posts/:num/"
